require: rubocop-rails

Rails:
  Enabled: true

Rails/HelperInstanceVariable:
  Exclude:
  - 'app/helpers/application_helper.rb'
  - 'app/helpers/cvs_helper.rb'

Rails/HasManyOrHasOneDependent:
  Exclude:
  - 'app/models/cv.rb'

Rails/FilePath:
  Exclude:
  - 'config/application.rb'
  - 'config/initializers/geocoder.rb'
  - 'config/environments/development.rb'
  - 'test/test_helper.rb'

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/UselessMethodDefinition:
  Exclude:
  - 'app/controllers/users/registrations_controller.rb'

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 33

Rails/SkipsModelValidations:
  Enabled: false

Style/WordArray:
  EnforcedStyle: percent
  MinSize: 8

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Exclude:
  - 'bin/setup'
  - 'bin/update'

Style/NonNilCheck:
  IncludeSemanticChanges: true

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*.rb'
  - 'config/routes.rb'

Metrics/ClassLength:
  Max: 250

Metrics/ModuleLength:
  Max: 140

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
  - 'bin/**/*'
  - 'script/**/*'
  - 'log/**/*'
  - 'public/**/*'
  - 'tmp/**/*'
  - 'db/**/*'
  - 'vendor/**/*'
  - 'node_modules/**/*'
  - 'lib/tasks/heroku_clear_tasks.rake'

inherit_from: .rubocop_todo.yml
